parameters:
    templates_path: %base_path%/../pages
    templates_cache: /tmp/twig

services:
    ptcorpus.twig.loader:
        class: Twig_Loader_Filesystem
        arguments:
            - %templates_path%

    ptcorpus.twig:
        class: Twig_Environment
        arguments:
            - @ptcorpus.twig.loader
            - [cache: %templates_cache%]
        calls:
            - ['addExtension', [@ptcorpus.twig.extension.freebase]]
            - ['addExtension', [@ptcorpus.twig.extension.page]]
            - ['addExtension', [@ptcorpus.twig.extension.grammar]]

    ptcorpus.freebase:
        class: Ptcorpus\Freebase

    ptcorpus.renderer:
        class: Ptcorpus\Renderer
        arguments:
            - @ptcorpus.twig

    ptcorpus.twig.extension.freebase:
        class: Ptcorpus\Twig\FreebaseExtension
        arguments:
            - @ptcorpus.freebase

    ptcorpus.twig.extension.page:
        class: Ptcorpus\Twig\PageExtension

    ptcorpus.twig.extension.grammar:
        class: Ptcorpus\Twig\GrammarExtension