parameters:
    templates_path: %base_path%/../pages
    templates_cache: /tmp/twig

services:
    ptcorpus.twig.loader:
        class: Twig_Loader_Filesystem
        arguments:
            - %templates_path%

    ptcorpus.twig:
        class: Twig_Environment
        arguments:
            - @ptcorpus.twig.loader
            # - {'cache': %templates_cache%}
        calls:
            - ['addExtension', [@ptcorpus.twig.extension.freebase]]
            - ['addExtension', [@ptcorpus.twig.extension.page]]
            - ['addExtension', [@ptcorpus.twig.extension.grammar]]
            - ['addExtension', [@ptcorpus.twig.extension.known]]
            - ['addExtension', [@ptcorpus.twig.extension.vary]]

    ptcorpus.freebase:
        class: Ptcorpus\Freebase
        arguments:
            - @guzzle.http.client

    guzzle.http.client:
        class: GuzzleHttp\Client

    ptcorpus.renderer:
        class: Ptcorpus\Renderer
        arguments:
            - @ptcorpus.twig

    ptcorpus.twig.extension.freebase:
        class: Ptcorpus\Twig\FreebaseExtension
        arguments:
            - @ptcorpus.freebase

    ptcorpus.twig.extension.page:
        class: Ptcorpus\Twig\PageExtension

    ptcorpus.twig.extension.grammar:
        class: Ptcorpus\Twig\GrammarExtension

    ptcorpus.twig.extension.known:
        class: Ptcorpus\Twig\KnownExtension

    ptcorpus.twig.extension.vary:
        class: Ptcorpus\Twig\VaryExtension

    ptcorpus.page_parser:
        class: Ptcorpus\PageParser

    ptcorpus.related_articles:
        class: Ptcorpus\RelatedArticles
        arguments:
            - @ptcorpus.page_parser

    ptcorpus.staff_picks:
        class: Ptcorpus\StaffPicks
        arguments:
            - @ptcorpus.page_parser